server:
  port: 8189
  servlet:
    context-path: /market-core

spring:
  flyway:
    locations: classpath:/db/testdata
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

integrations:
  cart-service:
    url: http://localhost:8190/market-carts/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000

pagination:
  page:
    size:
      default: 5

paypal:
  client-id: AZX9sEz_m_KSN8L6yOcKLZMq4BJ5bJ1uRpNzPE_5PqswQIRysphIDBii578puqKFxEEP-3QoK5O6Kk94
  client-secret: EIxWWhYStUGs3iWpMXT98Tpv4_kq-LSUl3XYa2BSvzfok_agUpDBDkGYzabP2XdbJ6y4fdaY